import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import '../version.dart';
import 'app_reload_stub.dart'
    if (dart.library.js_interop) 'app_reload_web.dart'
    as reload;

/// Watches the deployed `version.json` (generated by every `flutter build
/// web`) and flips [updateAvailable] when it differs from the compiled-in
/// [kAppVersion], so a long-lived tab can prompt for a reload.
///
/// Web-only in effect: [start] is a no-op elsewhere, since a native app can't
/// fetch "its own" hosting URL nor reload itself.
class UpdateChecker extends ChangeNotifier {
  UpdateChecker({Future<String?> Function()? fetchVersion})
    : _fetchVersion = fetchVersion ?? _fetchDeployedVersion;

  /// How often a long-lived tab re-checks. Each check is a ~100-byte fetch.
  static const Duration checkInterval = Duration(minutes: 5);

  final Future<String?> Function() _fetchVersion;
  Timer? _timer;
  bool _updateAvailable = false;

  bool get updateAvailable => _updateAvailable;

  /// Check now and keep checking every [checkInterval]. No-op off web.
  void start() {
    if (!kIsWeb) return;
    unawaited(check());
    _timer ??= Timer.periodic(checkInterval, (_) => check());
  }

  /// One poll of version.json. Failures are ignored — staleness detection
  /// must never break the app.
  Future<void> check() async {
    if (_updateAvailable) return; // already prompting; nothing to add
    try {
      final deployed = await _fetchVersion();
      if (deployed != null && deployed != kAppVersion) {
        _updateAvailable = true;
        notifyListeners();
      }
    } catch (_) {}
  }

  /// Reload the page to pick up the new version (web builds).
  void applyUpdate() => reload.reloadApp();

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }

  static Future<String?> _fetchDeployedVersion() async {
    // ?ts= busts any intermediary cache; hosting also serves no-cache.
    final uri = Uri.base.resolve(
      'version.json?ts=${DateTime.now().millisecondsSinceEpoch}',
    );
    final response = await http.get(uri);
    if (response.statusCode != 200) return null;
    final data = jsonDecode(response.body) as Map<String, dynamic>;
    return data['version'] as String?;
  }
}
