// Bumps the patch component of the app version and keeps lib/version.dart in
// sync with pubspec.yaml.
//
//   dart run tool/bump_version.dart
//
// pubspec.yaml is the source of truth (marketing version + build number for the
// app stores). lib/version.dart holds the display-only marketing version that is
// compiled into the app (the badge in the home screen corner).
import 'dart:io';

final _pubspecVersion = RegExp(r'^version:\s*(\S+)\s*$', multiLine: true);
final _versionPattern = RegExp(r'^(\d+)\.(\d+)\.(\d+)(?:\+(\d+))?$');

/// Bumps the patch (third) component and the build number by one.
/// `'0.0.1+1'` -> `'0.0.2+2'`; a missing build number starts at 1.
String bumpPatchVersion(String current) {
  final match = _versionPattern.firstMatch(current.trim());
  if (match == null) {
    throw FormatException('Invalid version string: "$current"');
  }
  final major = int.parse(match.group(1)!);
  final minor = int.parse(match.group(2)!);
  final patch = int.parse(match.group(3)!) + 1;
  final buildGroup = match.group(4);
  final build = (buildGroup == null ? 0 : int.parse(buildGroup)) + 1;
  return '$major.$minor.$patch+$build';
}

/// The display-only marketing version (`x.y.z`), stripping any `+build` suffix.
String marketingVersion(String version) {
  final match = _versionPattern.firstMatch(version.trim());
  if (match == null) {
    throw FormatException('Invalid version string: "$version"');
  }
  return '${match.group(1)}.${match.group(2)}.${match.group(3)}';
}

void main() {
  final pubspecFile = File('pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    stderr.writeln('pubspec.yaml not found — run from the project root.');
    exit(1);
  }

  final pubspec = pubspecFile.readAsStringSync();
  final match = _pubspecVersion.firstMatch(pubspec);
  if (match == null) {
    stderr.writeln('Could not find a "version:" line in pubspec.yaml.');
    exit(1);
  }

  final current = match.group(1)!;
  final next = bumpPatchVersion(current);

  pubspecFile.writeAsStringSync(
    pubspec.replaceRange(match.start, match.end, 'version: $next'),
  );

  File('lib/version.dart').writeAsStringSync(
    '// GENERATED by tool/bump_version.dart — do not edit by hand.\n'
    "const String kAppVersion = '${marketingVersion(next)}';\n",
  );

  stdout.writeln('bumped $current -> $next');
}
